const types = [
  { value: "feat", name: "feat:     A new feature", emoji: ":sparkles:" },
  { value: "fix", name: "fix:      A bug fix", emoji: ":bug:" },
  { value: "docs", name: "docs:     Documentation only changes", emoji: ":memo:" },
  { value: "style", name: "style:    Formatting and style-only changes", emoji: ":lipstick:" },
  { value: "refactor", name: "refactor: Code changes without behavior changes", emoji: ":recycle:" },
  { value: "perf", name: "perf:     Performance improvements", emoji: ":zap:" },
  { value: "build", name: "build:    Build system or dependency changes", emoji: ":package:" },
  { value: "ci", name: "ci:       CI configuration changes", emoji: ":ferris_wheel:" },
  { value: "chore", name: "chore:    Maintenance changes", emoji: ":hammer:" },
  { value: "revert", name: "revert:   Revert a previous commit", emoji: ":rewind:" },
]

module.exports = {
  alias: {
    dn: "docs: update notes",
    nf: "fix(nvim): adjust configuration",
    np: "perf(nvim): improve startup performance",
  },
  messages: {
    type: "変更種別を選択:",
    scope: "スコープを選択 / なければ input / optional:",
    customScope: "スコープを入力 例: auth, api, db:",
    subject: "短い説明を入力 imperative / lower-case 推奨:\n",
    body: "詳細説明 optional。改行は | を使用:\n",
    breaking: "BREAKING CHANGE optional。改行は | を使用:\n",
    footerPrefixesSelect: "Footer prefixを選択。prefix不要なら none、なければ input:",
    customFooterPrefix: "Footer prefixを入力 例: Refs, Closes, Co-authored-by:",
    footer: "Footer本文 optional。例: #31, user@example.com:\n",
    confirmCommit: "この内容でコミットしますか?",
  },
  types,
  scopes: [
    "api",
    "auth",
    "db",
    "ui",
    "ux",
    "deps",
    "config",
    "infra",
    "ci",
    "test",
    "docs",
    "release",
    "nvim",
    "git",
    "lazygit",
    "nix",
    "shell",
    "devops",
  ],
  allowCustomScopes: true,
  allowEmptyScopes: true,
  customScopesAlign: "bottom",
  customScopesAlias: "custom",
  emptyScopesAlias: "empty",
  useEmoji: false,
  emojiAlign: "center",
  upperCaseSubject: null,
  allowBreakingChanges: ["feat", "fix"],
  breaklineNumber: 100,
  breaklineChar: "|",
  issuePrefixes: [
    { value: "", name: "none:          Use footer text as-is" },
    { value: "Refs", name: "Refs:          Reference issue/PR" },
    { value: "Closes", name: "Closes:        Close issue/PR" },
    { value: "Fixes", name: "Fixes:         Fix issue/PR" },
    { value: "Co-authored-by", name: "Co-authored-by: Pair/mob author" },
    { value: "Reviewed-by", name: "Reviewed-by:    Reviewer trailer" },
    { value: "Signed-off-by", name: "Signed-off-by:  DCO trailer" },
  ],
  allowCustomIssuePrefix: true,
  allowEmptyIssuePrefix: true,
  customIssuePrefixAlign: "bottom",
  emptyIssuePrefixAlias: "skip",
  customIssuePrefixAlias: "input",
  confirmColorize: true,
}
