const types = [
  { value: "feat", name: "feat:     A new feature", emoji: ":sparkles:" },
  { value: "fix", name: "fix:      A bug fix", emoji: ":bug:" },
  { value: "docs", name: "docs:     Documentation only changes", emoji: ":memo:" },
  { value: "style", name: "style:    Formatting and style-only changes", emoji: ":lipstick:" },
  { value: "refactor", name: "refactor: Code changes without behavior changes", emoji: ":recycle:" },
  { value: "perf", name: "perf:     Performance improvements", emoji: ":zap:" },
  { value: "build", name: "build:    Build system or dependency changes", emoji: ":package:" },
  { value: "ci", name: "ci:       CI configuration changes", emoji: ":ferris_wheel:" },
  { value: "chore", name: "chore:    Maintenance changes", emoji: ":hammer:" },
  { value: "revert", name: "revert:   Revert a previous commit", emoji: ":rewind:" },
]

module.exports = {
  alias: {
    dn: "docs: update notes",
    nf: "fix(nvim): adjust configuration",
    np: "perf(nvim): improve startup performance",
  },
  messages: {
    type: "変更種別を選択:",
    scope: "スコープを選択または入力 optional:",
    customScope: "スコープを入力:",
    subject: "短い説明を入力 imperative / lower-case 推奨:\n",
    body: "詳細説明 optional。改行は | を使用:\n",
    breaking: "BREAKING CHANGE optional。改行は | を使用:\n",
    footerPrefixesSelect: "Issue prefix optional:",
    customFooterPrefix: "Issue prefixを入力:",
    footer: "関連Issue optional。例: #31, #34:\n",
    confirmCommit: "この内容でコミットしますか?",
  },
  types,
  scopes: [
    "nvim",
    "git",
    "lazygit",
    "nix",
    "shell",
    "wezterm",
    "yazi",
    "zellij",
    "sketchybar",
    "raycast",
    "docs",
    "infra",
    "backend",
    "frontend",
    "bug",
    "devops",
    "api",
  ],
  allowCustomScopes: true,
  allowEmptyScopes: true,
  customScopesAlign: "bottom",
  customScopesAlias: "custom",
  emptyScopesAlias: "empty",
  useEmoji: false,
  emojiAlign: "center",
  upperCaseSubject: false,
  allowBreakingChanges: ["feat", "fix"],
  breaklineNumber: 100,
  breaklineChar: "|",
  issuePrefixes: [
    { value: "close", name: "close:    Close issue" },
    { value: "fix", name: "fix:      Fix issue" },
    { value: "ref", name: "ref:      Reference issue" },
  ],
  allowCustomIssuePrefix: true,
  allowEmptyIssuePrefix: true,
  emptyIssuePrefixAlias: "skip",
  customIssuePrefixAlias: "custom",
  confirmColorize: true,
}
