"$schema" = 'https://starship.rs/config-schema.json'
palette = "fuji_dark"

format = """
$directory\
[󰣇 ](fg:blue)\
$git_branch\
$git_state\
$git_status\
$fill\
\n$character
"""

right_format = """
$status\
$jobs\
$username\
${custom.language_stack}\
$time
"""

# コマンドラインに1行分のスペースを入れる
add_newline = true

[palettes.fuji_dark]
base = "#001829"
surface = "#123047"
accent = "#4C8FA9"
accent_bright = "#5C9BB3"
blue = "#84A0C6"
purple = "#A093C7"
text = "#8FBFBB"
cyan = "#89B8C2"
muted = "#7A9BAD"
success = "#8BBF9F"
error = "#CC7A8B"

[username]
style_user = "fg:text bold"
style_root = "fg:error bold"
format = "[$user]($style) "
disabled = false
show_always = false


# left_promptとright_promptの間を何で埋めるか設定
[fill]
symbol = ' '

[directory]
style = "fg:text"
# format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"
# truncation_symbol = ' ' # nf-fa-folder_open
# truncate_to_repo = false
# style = 'fg:#7aa2f7 bg:#1a1b26'
read_only = ' 󰌾 ' # nf-md-lock
read_only_style = 'fg:error'
format = '[$path]($style)[$read_only]($read_only_style) '


[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
disabled = true
[gcloud]
disabled = true

[custom.language_stack]
command = "~/.config/scripts/starship-language-context"
when = true
style = "fg:cyan"
format = "([](fg:surface)[ $output ](fg:cyan bg:surface)[](fg:surface) )"

[git_branch]
symbol = " "
style = "fg:blue"
format = '[$symbol$branch]($style) '
truncation_length = 24
truncation_symbol = "…"

[git_state]
style = "fg:purple"
format = "[$state( $progress_current/$progress_total)]($style) "

[git_status]
style = "fg:cyan"
format = '([$all_status$ahead_behind]($style) )'
conflicted = "[=${count}](fg:error)"
ahead = "[⇡${count}](fg:blue)"
behind = "[⇣${count}](fg:blue)"
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](fg:purple)"
untracked = "[?${count}](fg:purple)"
stashed = "[≡${count}](fg:purple)"
modified = "[!${count}](fg:purple)"
staged = "[+${count}](fg:success)"
renamed = "[»${count}](fg:cyan)"
deleted = "[✘${count}](fg:error)"
typechanged = "[~${count}](fg:purple)"

[cmd_duration]
min_time = 2000
style = "fg:purple"
format = "[󰑮 $duration]($style) "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:muted"
format = "[󱦟 $time]($style)"

[jobs]
symbol = "✦ "
number_threshold = 1
symbol_threshold = 1
style = "fg:blue"
format = "[$symbol$number]($style) "

[status]
disabled = false
symbol = "✗ "
style = "fg:error bold"
format = "[$symbol$status]($style) "

[character]
success_symbol = "[❯](bold fg:blue)"
error_symbol = "[❯](bold fg:error)"
vimcmd_symbol = '[V](bold fg:purple) '
