gui:
  theme:
    activeBorderColor:
      - "#7AA2F7"
      - bold
    inactiveBorderColor:
      - "#565F89"
    optionsTextColor:
      - "#E0AF68"
    selectedLineBgColor:
      - "#292E42"
    cherryPickedCommitBgColor:
      - "#3D59A1"
    cherryPickedCommitFgColor:
      - "#BB9AF7"
    unstagedChangesColor:
      - "#F7768E"
    defaultFgColor:
      - "#C0CAF5"
    searchingActiveBorderColor:
      - "#7DCFFF"
      - bold
  authorColors:
    "*": "#BB9AF7"
git:
  # git log
  branchLogCmd: "git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' {{branchName}} --"
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --side-by-side
  allBranchesLogCmds:
    - git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --all
customCommands:
  - key: "G"
    context: "files"
    description: "Commit with czg"
    command: "czg --config=$HOME/.config/cz.config.cjs"
    output: terminal
