gui:
  theme:
    activeBorderColor:
      - "#5C9BB3"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#1F4B66"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  authorColors:
    "*": "#b4befe"
git:
  # git log
  branchLogCmd: "git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' {{branchName}} --"
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --side-by-side
  allBranchesLogCmds:
    - git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --all
customCommands:
  - key: "G"
    context: "files"
    description: "Commit with czg"
    command: "czg --config=$HOME/.config/cz.config.cjs"
    output: terminal
